<img src=images/gdd-logo.png width=300px align=right> 

# Filtering

In this notebook, we will cover how to filter data.

- [Filtering](#f)
   - [Using (lambda) functions to filter](#lambdas)
   - <mark>[Exercise: Filtering](#e-filter)</mark>
- [Multiple Conditions](#m)
    - <mark>[Exercise: Multiple Conditions](#e-mult)</mark>

In [2]:
import pandas as pd

chickweight = pd.read_csv('data/chickweight.csv').rename(str.lower, axis='columns')

<a id='f'></a>
## Filtering

It is possible to check whether the DataFrame/series meet certain conditions. 

For example, *which values in the chickweight DataFrame are less than 4?*

In [3]:
(
    chickweight < 4
).head()

   rownum  weight   time  chick  diet
0    True   False   True   True  True
1    True   False   True   True  True
2    True   False  False   True  True
3   False   False  False   True  True
4   False   False  False   True  True

Probably more useful would be to check one column at a time:

In [3]:
(
    chickweight['time'] < 4
)

0       True
1       True
2      False
3      False
4      False
       ...
573    False
574    False
575    False
576    False
577    False
Name: time, Length: 578, dtype: bool

This creates a boolean mask (a list of booleans). 

A second type of argument that the `.loc[]` method accepts is a boolean mask, so we can use it to filter our DataFrame.

In [12]:
(
    chickweight
    .loc[chickweight['time'] < 4]
)

     rownum  weight  time  chick  diet
0         1      42     0      1     1
1         2      51     2      1     1
12       13      40     0      2     1
13       14      49     2      2     1
24       25      43     0      3     1
..      ...     ...   ...    ...   ...
543     544      50     2     48     4
554     555      40     0     49     4
555     556      53     2     49     4
566     567      41     0     50     4
567     568      54     2     50     4

[100 rows x 5 columns]

### <mark> Practice: Filtering </mark>


Filter the data in the following ways:

1. For when weight is less than 60.

In [22]:
chickweight.loc[chickweight['weight'] < 60]

     rownum  weight  time  chick  diet
0         1      42     0      1     1
1         2      51     2      1     1
2         3      59     4      1     1
12       13      40     0      2     1
13       14      49     2      2     1
..      ...     ...   ...    ...   ...
543     544      50     2     48     4
554     555      40     0     49     4
555     556      53     2     49     4
566     567      41     0     50     4
567     568      54     2     50     4

[127 rows x 5 columns]

2. For chick number 15.

In [24]:
chickweight.loc[chickweight['chick'] == 20]

     rownum  weight  time  chick  diet
208     209      41     0     20     1
209     210      47     2     20     1
210     211      54     4     20     1
211     212      58     6     20     1
212     213      65     8     20     1
213     214      73    10     20     1
214     215      77    12     20     1
215     216      89    14     20     1
216     217      98    16     20     1
217     218     107    18     20     1
218     219     115    20     20     1
219     220     117    21     20     1

In [27]:
chickweight['time'].describe()

count    578.000000
mean      10.717993
std        6.758400
min        0.000000
25%        4.000000
50%       10.000000
75%       16.000000
max       21.000000
Name: time, dtype: float64

In [18]:
# %load answers/02_Selections_and_Filtering/filter-practice.py

(
    chickweight
    .loc[chickweight['weight'] < 60]
)

(
    chickweight
    .loc[chickweight['chick'] == 15]
)

<a id = 'lambdas'></a>
## Using (lambda) functions to filter

The third type or argument that the `.loc[]` method accepts is a function that takes a DataFrame and returns a boolean mask. This function will get called on **whatever DataFrame arrives to the `.loc[]`**.

This allows you to add many filters without needing to reference the original name of the DataFrame:

In [34]:
(
    chickweight  
    .loc[lambda df: df['chick'] == 1]
    .loc[lambda df: df['time'] < 4] 
)

   rownum  weight  time  chick  diet
0       1      42     0      1     1
1       2      51     2      1     1

What are the benefits of using lambda functions when filtering?

<details>
    <summary><font color=blue>Show answer</font></summary>
    
- Your code works independently of the name of the dataframe (easy to copy-paste!).
- You can filter on new columns that were created in the step before.
- You can re-order filters, they work with whatever DataFrame arrives to the filter, as long as the column needed exists.

**A note about lambda functions**: The lambda function may feel a little strange at this stage but, trust us, when you start to add more chains, the lambda function will really save the day!

For now it's important to be comfortable with the syntax, so let's practice!

<a id='e-filter'></a>
## <mark> Exercise: Filtering </mark>


Filter the data in the following (separate) ways:

1. For when weight is greater than 150.

In [30]:
chickweight.loc[chickweight['weight'] > 150]

     rownum  weight  time  chick  diet
9        10     171    18      1     1
10       11     199    20      1     1
11       12     205    21      1     1
20       21     162    16      2     1
21       22     187    18      2     1
..      ...     ...   ...    ...   ...
573     574     175    14     50     4
574     575     205    16     50     4
575     576     234    18     50     4
576     577     264    20     50     4
577     578     264    21     50     4

[178 rows x 5 columns]

2. For diet is equal to 4.

In [31]:
chickweight.loc[chickweight['diet'] == 4]

     rownum  weight  time  chick  diet
460     461      42     0     41     4
461     462      51     2     41     4
462     463      66     4     41     4
463     464      85     6     41     4
464     465     103     8     41     4
..      ...     ...   ...    ...   ...
573     574     175    14     50     4
574     575     205    16     50     4
575     576     234    18     50     4
576     577     264    20     50     4
577     578     264    21     50     4

[118 rows x 5 columns]

3. For when weight is less than 60 and time is equal to 2.

In [33]:
(
    chickweight  
    .loc[lambda df: df['weight'] < 60]
    .loc[lambda df: df['time'] == 2] 
)

     rownum  weight  time  chick  diet
1         2      51     2      1     1
13       14      49     2      2     1
25       26      39     2      3     1
37       38      49     2      4     1
49       50      42     2      5     1
61       62      49     2      6     1
73       74      49     2      7     1
85       86      50     2      8     1
96       97      51     2      9     1
108     109      44     2     10     1
120     121      51     2     11     1
132     133      49     2     12     1
144     145      48     2     13     1
156     157      49     2     14     1
168     169      49     2     15     1
176     177      45     2     16     1
183     184      51     2     17     1
195     196      35     2     18     1
197     198      48     2     19     1
209     210      47     2     20     1
221     222      50     2     21     2
233     234      55     2     22     2
245     246      52     2     23     2
257     258      52     2     24     2
269     270      49     2     25     2
281     282      48     2     26     2
293     294      46     2     27     2
305     306      46     2     28     2
317     318      48     2     29     2
329     330      48     2     30     2
341     342      53     2     31     3
353     354      49     2     32     3
365     366      50     2     33     3
377     378      49     2     34     3
389     390      53     2     35     3
401     402      48     2     36     3
413     414      48     2     37     3
425     426      49     2     38     3
437     438      50     2     39     3
449     450      55     2     40     3
461     462      51     2     41     4
473     474      49     2     42     4
485     486      55     2     43     4
497     498      51     2     44     4
507     508      50     2     45     4
519     520      52     2     46     4
531     532      53     2     47     4
543     544      50     2     48     4
555     556      53     2     49     4
567     568      54     2     50     4

4. For when weight is less than 60 and time is equal to 2, but only the weight and time columns.

In [45]:
(
    chickweight  
    .loc[lambda df: df['weight'] < 60]
    .loc[lambda df: df['time'] == 2, ['weight', "time"]]
)

     weight  time
1        51     2
13       49     2
25       39     2
37       49     2
49       42     2
61       49     2
73       49     2
85       50     2
96       51     2
108      44     2
120      51     2
132      49     2
144      48     2
156      49     2
168      49     2
176      45     2
183      51     2
195      35     2
197      48     2
209      47     2
221      50     2
233      55     2
245      52     2
257      52     2
269      49     2
281      48     2
293      46     2
305      46     2
317      48     2
329      48     2
341      53     2
353      49     2
365      50     2
377      49     2
389      53     2
401      48     2
413      48     2
425      49     2
437      50     2
449      55     2
461      51     2
473      49     2
485      55     2
497      51     2
507      50     2
519      52     2
531      53     2
543      50     2
555      53     2
567      54     2

**BONUS**:

1. Calculate the mean (= average) Chicken weight.

In [47]:
(
    chickweight['weight']
    .mean()
)

121.81833910034602

2. Calculate the mean Chicken weight at time 10

In [52]:
(
    chickweight
    .loc[lambda df: df["time"] == 10, "weight"]
    .mean()

)

107.83673469387755

**Answers**

In [46]:
# %load answers/02_Selections_and_Filtering/filtering.py

# 1
(
    chickweight
    .loc[lambda df: df['weight'] > 150]
)

# 2
(
    chickweight
    .loc[lambda df: df['diet'] == 4]
)

# 3
(
    chickweight
    .loc[lambda df: df['time'] == 2]
    .loc[lambda df: df['weight'] < 60]
)

# 4
(
    chickweight
    .loc[lambda df: df['weight'] < 60, ['weight', 'time']]
    .loc[lambda df: df['time'] == 2]
)

# bonus 1
(
    chickweight['weight']
    .mean()
)

# bonus 2
(
    chickweight
    .loc[lambda df: df['time'] == 10, "weight"]
    .mean()
)

<a id='m'></a>
## Multiple conditions


Let's have a look now at how to use multiple conditions within the same line. Aside from being more efficient to run, it is also useful as there is no need to worry about previous filters.

In [53]:
(
    chickweight
    .loc[lambda df: (df['chick'] == 1) & (df['weight'] < 50)]
)

   rownum  weight  time  chick  diet
0       1      42     0      1     1

In [61]:
(chickweight["chick"] == 1) | (chickweight["time"] == 2)

0       True
1       True
2       True
3       True
4       True
       ...
573    False
574    False
575    False
576    False
577    False
Length: 578, dtype: bool

***Note the need for parentheses and the use of `&` rather than `and`?***

Firstly, the **parentheses** are needed due to the order of operations, `&` always performs before comparisons like `==`, `<`, `>=` etc.

**Now for `&` vs `and`...** the use of `and` can be used to test whether both expressions written are logically `True`. Eg:

In [ ]:
True and True

In [ ]:
True and False

In [ ]:
False and True

In [ ]:
False and False

But entire boolean mask isn't  `True` or `False`, it's a **list** of `True`/`False` values:

In [ ]:
chickweight['chick'] == 1

In [ ]:
# # error
# (
#     chickweight
#     .loc[lambda df: (df['chick'] == 1) and (df['weight'] < 50)]
# )

You can use `&`, the bitwise AND operation to compare each `True`/`False` in every row with multiple filters.

In [ ]:
(
    chickweight
    [["chick", "weight"]]
    .loc[lambda df: (df['chick'] == 1) & (df['weight'] < 50)]
)

**The `&` (ampersand) only equates to <span style=color:green>True</span> if BOTH conditions are met:**

![](images/02_Selections_and_Filtering/filt-and.png)

In [ ]:
(
    chickweight
    .loc[lambda df: (df['chick'] == 1) | (df['weight'] < 50)]
    .head(15)
)

**The `|` (pipe) equates to <span style=color:green>True</span> if AT LEAST ONE condition is met:**

![](images/02_Selections_and_Filtering/filt-or.png)

In [62]:
(
    chickweight
    .loc[lambda df: (df['chick'] == 1) ^ (df['weight'] < 50)]
    .head(15)
)

    rownum  weight  time  chick  diet
1        2      51     2      1     1
2        3      59     4      1     1
3        4      64     6      1     1
4        5      76     8      1     1
5        6      93    10      1     1
6        7     106    12      1     1
7        8     125    14      1     1
8        9     149    16      1     1
9       10     171    18      1     1
10      11     199    20      1     1
11      12     205    21      1     1
12      13      40     0      2     1
13      14      49     2      2     1
24      25      43     0      3     1
25      26      39     2      3     1

**The `^` (hat) equates to <span style=color:green>True</span> if ONLY ONE condition is met:**

![](images/02_Selections_and_Filtering/filt-hat.png)

<a id='e-mult'></a>
## <mark> Exercise: Multiple conditions </mark>

Select only the part of chickweight where:

1. **weight** is above 50 but below 100.

In [4]:
(
    chickweight
    .loc[lambda df: (df['weight'] > 50) & (df['weight'] < 100)]
)

     rownum  weight  time  chick  diet
1         2      51     2      1     1
2         3      59     4      1     1
3         4      64     6      1     1
4         5      76     8      1     1
5         6      93    10      1     1
..      ...     ...   ...    ...   ...
556     557      64     4     49     4
557     558      85     6     49     4
567     568      54     2     50     4
568     569      67     4     50     4
569     570      84     6     50     4

[189 rows x 5 columns]

2. **diet** is either 1 or 2.

In [11]:
(
    chickweight
    .loc[lambda df: (df['diet'] == 1) | (df['diet'] == 2)]
)

     rownum  weight  time  chick  diet
0         1      42     0      1     1
1         2      51     2      1     1
2         3      59     4      1     1
3         4      64     6      1     1
4         5      76     8      1     1
..      ...     ...   ...    ...   ...
335     336     122    14     30     2
336     337     143    16     30     2
337     338     151    18     30     2
338     339     157    20     30     2
339     340     150    21     30     2

[340 rows x 5 columns]

3. For when weight is less than 60 and time is equal to 2, but only the weight and time columns!

In [13]:
(
    chickweight
    .loc[lambda df: (df['weight'] < 60) & (df['time'] == 2), ['weight', "time"]]
)

     weight  time
1        51     2
13       49     2
25       39     2
37       49     2
49       42     2
61       49     2
73       49     2
85       50     2
96       51     2
108      44     2
120      51     2
132      49     2
144      48     2
156      49     2
168      49     2
176      45     2
183      51     2
195      35     2
197      48     2
209      47     2
221      50     2
233      55     2
245      52     2
257      52     2
269      49     2
281      48     2
293      46     2
305      46     2
317      48     2
329      48     2
341      53     2
353      49     2
365      50     2
377      49     2
389      53     2
401      48     2
413      48     2
425      49     2
437      50     2
449      55     2
461      51     2
473      49     2
485      55     2
497      51     2
507      50     2
519      52     2
531      53     2
543      50     2
555      53     2
567      54     2

**Answers**

In [ ]:
# %load answers/02_Selections_and_Filtering/multiple_conditions.py

### 🔍 Filtering Data in Pandas - Quick Summary

Filtering helps you **zoom in on the rows you care about**. Use `.loc[]` to select rows based on conditions.

- Use comparisons to filter:
  ```python
  my_data.loc[lambda df: df['column'] > 50]
  ```

- Combine multiple conditions with:
  - `&` for **AND**
  - `|` for **OR**
  - Wrap each condition in `()`
    
```python
my_data.loc[lambda df: (df['col1'] > 50) & (df['col2'] < 100)]
```


✅ Helps focus on the right data  
✅ Supports complex logic  
✅ Clean and readable with `lambda` + `.loc[]` combo

_Filtering is all about asking good questions and using code to get the right slice of data!_